version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    networks:
      - nginx_network
      - database_network
    depends_on:
      - appdb
    env_file:
      - .env
      
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/code/static
      - media_volume:/code/media 
    depends_on:
      - web
    networks:
      - nginx_network

  appdb:
    image: postgres:10
    env_file:
      - ./config/postgres/database_env
    ports:
      - 15432:5432
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data
    
            
networks:
  nginx_network:
    driver: bridge

  database_network:
    driver: bridge

volumes:
  database_volume:
  static_volume:
  media_volume:
