# Generated by Django 2.0.5 on 2019-04-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190403_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='UN BUEN CAFE PARA TOMAR EN FAMILIA', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slogan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
